# Generated by Django 3.2.7 on 2021-11-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cateogry',
            field=models.CharField(choices=[('wk', '근무 이야기'), ('lf', '일상 이야기'), ('fn', '머니 이야기'), ('qt', '질문 이야기')], default='wk', max_length=2),
        ),
    ]
