# Generated by Django 3.2.7 on 2021-11-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='cateogry',
            new_name='category',
        ),
    ]
